### PR TITLE
Introduce slide-in effect when scrolling down

### PR DESCRIPTION
**Pull request by dinuand**
You can quickly preview the changes by accessing [link-to-preview](http://89.120.219.189:4000) until midnight. The slide-in effect is available in Firefox, Chrome or Safari.

What do you think? It's ok if we introduce this effect to our CDL website?

### CODE REVIEW

**Comment by Therzok** [comment]
The page feels considerably slower.

**Comment by dinuand** [comment]
One reason for this could be that the server is a local jekyll one, on my laptop and the net speed is not so fast. 
Even with the actual version of the site, if I put it on a local server and then make a port forward, 
will feel slower than [http://cdl.rosedu.org](http://cdl.rosedu.org), too. You could try it here: [link-to-official-version](http://89.120.219.189:8000).
And here is the [link-to-preview](http://89.120.219.189:4000).

@Therzok , still the same impression?

**Comment by Therzok** [comment]
Yes. It's probably caused by Mac's smooth scrolling. Anyway, I guess people can bare with it, as it's just one 100-ish ms stutter per scroll.

**Comment by calincru** [comment]
LGTM overall. One thing could be improved, though: clicking the logo on the top left corner makes a jump to the "Home page" with no slide-in effect. Is this what we want?

**Comment by dinuand** [comment]
@edi33416 , could you take care, please, of what @calincru mentioned above and then create a PR?
@calincru , that is a scroll-to effect.

**Comment by edi33416** [comment]
@dinuand, @calincru

Sorry for the late reply but I was out of town :)

I will do the changes right now.

Have a great weekend,
Edi

**Pull request merged**
